/* Parametros: 
PARAM_1: 'AGUINALDO'|'BONO14'|'OTROS'
PARAM_2: GRUPO DE ELEMENTOS
PARAM_3: CANTIDAD DE MESES 
PARAM_4: 1->MESES COMPLETO COFIÑO, 0->TODOS LOS MESES
PARAM_5: Devuelve: 0->Promedio, 1->Acumulado, 2->Dias, 3->Meses
*/
DECLARE @TIPO_PRESTACION NVARCHAR(10) = @PARAM_1
DECLARE @ElementGroupId NVARCHAR(60) = @PARAM_2
DECLARE @CANTIDAD INT = CONVERT(INT,@PARAM_3)
DECLARE @PROMEDIO_COFIÑO INT = CONVERT(INT,@PARAM_4)
DECLARE @TIPO_RETORNO INT = @PARAM_5

DECLARE @FechaInicial DATE
DECLARE @FechaFinal DATE
DECLARE @FechaInicialMes DATE
DECLARE @FechaFinalMes DATE
DECLARE @FechaAguinaldo DATE = NULL
DECLARE @FechaBono DATE = NULL

DECLARE @ElementId NVARCHAR(60)
DECLARE @ElementType INT
DECLARE @SUMAINGRESOS REAL = 0
DECLARE @ACUMULADO REAL = 0
DECLARE @ACUMULADODIAS INT = 0
DECLARE @DIAS INT
DECLARE @DIASMES INT = 0
DECLARE @CONTAMES INT = 0
DECLARE @TransId NVARCHAR(20)

DECLARE @EsPrimerDia BIT
DECLARE @VAR1 INT

IF @TIPO_RETORNO = NULL
BEGIN
    SET @TIPO_RETORNO = 0
END

IF @TIPO_PRESTACION = 'AGUINALDO' OR @TIPO_PRESTACION = 'BONO14'
BEGIN
    SELECT @FechaAguinaldo = t1.LASTAGUINALDO,
        @FechaBono = t1.LASTBONO14
    FROM PAYROLLEMPL t1
    WHERE t1.EMPLID = '%12'
    AND t1.DATAAREAID = '%1'

    IF @TIPO_PRESTACION = 'AGUINALDO'
    BEGIN
        IF @FechaAguinaldo = NULL OR @FechaAguinaldo = CONVERT(DATE,'01/01/1900',103)
            SET @FechaInicial = CONVERT(DATE,'%19',103)
        ELSE
            SET @FechaInicial = @FechaAguinaldo
    END
    IF @TIPO_PRESTACION = 'BONO14'
    BEGIN
        IF @FechaBono = NULL OR @FechaBono = CONVERT(DATE,'01/01/1900',103)
            SET @FechaInicial = CONVERT(DATE,'%19',103)
        ELSE
            SET @FechaInicial = @FechaBono
    END

    IF @FechaInicial < CONVERT(DATE,'%19',103)
        SET @FechaInicial = CONVERT(DATE,'%19',103)
END
ELSE
BEGIN
    SET @FechaInicial = DATEADD(MONTH,(@CANTIDAD*-1),CONVERT(DATE,'%8',103))

    IF @FechaInicial < CONVERT(DATE,'%19',103)
        SET @FechaInicial = CONVERT(DATE,'%19',103)
END

SET @FechaFinal = DATEADD(DAY,-1,CONVERT(DATE,'%8',103))

IF @PROMEDIO_COFIÑO = 1
BEGIN
    -- Verificar si la fecha inicial es el primer día del mes
    SET @EsPrimerDia = CASE 
        WHEN DAY(@FechaInicial) = 1 THEN 1 
        ELSE 0 
    END

    IF @EsPrimerDia = 0
    BEGIN
        SET @FechaInicial = DATEADD(DAY,1,EOMONTH(@FechaInicial))
    END
END

DECLARE PayRollTransEmplElement_Cursor CURSOR FOR
    select 
        SUM(ROUND(t1.amount,2)) ingresos, 
        SUM(t1.quantity) cantidad,
        t2.FROMDATE, t2.TODATE, t2.TRANSID
    from PAYROLLTRANSEMPLELEMENT t1
    join PAYROLLTRANS t2 on t1.TRANSID = t2.TRANSID
        and t1.DATAAREAID = t2.DATAAREAID
    where t1.ELEMENTID IN (SELECT ElementId
        FROM PayRollElementPerGroup
        WHERE ElementGroupId = @ElementGroupId
        AND DATAAREAID = '%1')
    AND t1.ELEMENTTYPE = 0
    and t1.EMPLID = '%12'
    AND ((t2.FROMDATE <= @FechaInicial
        AND t2.TODATE >= @FechaInicial)
        OR (t2.FROMDATE >= @FechaInicial
        AND t2.TODATE <= @FechaFinal)
        OR (t2.FROMDATE <= @FechaFinal
        AND t2.TODATE >= @FechaFinal))
    and t2.STATUS >= 6
    AND t1.DATAAREAID = '%1'
    group by t2.FROMDATE, t2.TODATE, t2.TRANSID

OPEN PayRollTransEmplElement_Cursor

FETCH NEXT FROM PayRollTransEmplElement_Cursor INTO @SUMAINGRESOS, @DIAS, @FechaInicialMes, @FechaFinalMes, @TransId

WHILE @@FETCH_STATUS = 0
BEGIN

    SET @DIASMES = DATEDIFF(DAY,@FechaInicialMes,@FechaFinalMes) + 1

    SET @DIAS = (SELECT SUM(t1.QUANTITY)
    FROM PAYROLLTRANSEMPLELEMENT t1
    WHERE t1.TRANSID = @TransId
    AND t1.EMPLID = '%12'
    AND t1.ELEMENTID IN ('SUELDO ORDINARIO','SUELDO ORDINARIO JUB','VACACIONES')
    AND t1.ELEMENTTYPE = 0
    AND t1.DATAAREAID = '%1')

    IF (@DIASMES <> @DIAS) AND (@PROMEDIO_COFIÑO = 1)
    BEGIN
        SET @VAR1= (SELECT COUNT(*) 
        FROM PAYROLLABSENCETRANS T1
        INNER JOIN PAYROLLABSENCETABLE T2 ON T1.PAYROLLABSENCETABLEID = T2.PAYROLLABSENCETABLEID 
            AND T1.DATAAREAID = T2.DATAAREAID
        WHERE T1.TRANSDATE BETWEEN @FechaInicialMes AND @FechaFinalMes
        AND T2.EMPLID = '%12'
        AND ( T1.PAYROLLABSENCECODEID in ('SUSP. IGSS','SUSP. MATERN') )
        AND T1.DATAAREAID = '%1') 

        IF (@VAR1 + @DIAS) <> (@DIASMES)
        BEGIN
            SET @ACUMULADO = @ACUMULADO + ROUND(@SUMAINGRESOS,2)
            SET @CONTAMES = @CONTAMES + 1
            SET @ACUMULADODIAS = @ACUMULADODIAS + @DIAS
        END
    END
    ELSE
    BEGIN
        SET @ACUMULADO = @ACUMULADO + ROUND(@SUMAINGRESOS,2)
        SET @CONTAMES = @CONTAMES + 1
        SET @ACUMULADODIAS = @ACUMULADODIAS + @DIAS
    END

    FETCH NEXT FROM PayRollTransEmplElement_Cursor INTO @SUMAINGRESOS, @DIAS, @FechaInicialMes, @FechaFinalMes, @TransId
END

CLOSE PayRollTransEmplElement_Cursor
DEALLOCATE PayRollTransEmplElement_Cursor


IF @TIPO_RETORNO = 0
BEGIN
    SELECT ROUND(@ACUMULADO / @CONTAMES,2)
END
IF @TIPO_RETORNO = 1
BEGIN
    SELECT @ACUMULADO
END
IF @TIPO_RETORNO = 2
BEGIN
    SELECT @ACUMULADODIAS
END
IF @TIPO_RETORNO = 3
BEGIN
    SELECT @CONTAMES
END