DECLARE @FechaInicio DATE = CONVERT(DATE,'%8',103)
DECLARE @FechaFinMesAnterior DATE = DATEADD(DAY,-1,@FechaInicio)
DECLARE @VAR1 INT = 0
DECLARE @VAR2 INT = 0
DECLARE @ABSENCECODE NVARCHAR(10) = @PARAM_1
DECLARE @RETURN INT

SET @VAR1= (SELECT COUNT(*) 
FROM PAYROLLABSENCETRANS T1
INNER JOIN PAYROLLABSENCETABLE T2 ON T1.PAYROLLABSENCETABLEID = T2.PAYROLLABSENCETABLEID 
WHERE T1.TRANSDATE = @FechaInicio
AND T2.EMPLID = '%12'
AND T1.PAYROLLABSENCECODEID = @ABSENCECODE)

IF @VAR1 = 0
BEGIN
    SET @RETURN = 1
END
ELSE
BEGIN
    SET @VAR2= (SELECT COUNT(*) 
    FROM PAYROLLABSENCETRANS T1
    INNER JOIN PAYROLLABSENCETABLE T2 ON T1.PAYROLLABSENCETABLEID = T2.PAYROLLABSENCETABLEID 
    WHERE T1.TRANSDATE = @FechaFinMesAnterior
    AND T2.EMPLID = '%12'
    AND T1.PAYROLLABSENCECODEID = @ABSENCECODE)

    IF @VAR2 = 0
    BEGIN
        SET @RETURN = 1
    END
    ELSE
    BEGIN
        SET @RETURN = 0
    END
END

SELECT @RETURN